import React, { useState } from "react";
import {
  FileText,
  Download,
  Copy,
  Check,
  Printer,
  X,
  BookOpen,
  HelpCircle,
  Lightbulb,
  CheckCircle2,
  Share2,
} from "lucide-react";

export default function StudyNotesModal({
  isOpen,
  onClose,
  lessonPlan,
  teacherName = "Dr. Maya",
  currentStepIndex = 0,
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !lessonPlan) return null;

  const topic = lessonPlan.topic || "Core Principles";
  const level = lessonPlan.learner_level || "beginner";
  const duration = lessonPlan.target_duration_minutes || 20;
  const steps = lessonPlan.steps || [];

  // Generate complete, structured markdown document
  const generateMarkdownNotes = () => {
    let md = `# Study Guide & Comprehensive Notes: ${topic}\n\n`;
    md += `> **Instructor:** ${teacherName} | **Level:** ${level.toUpperCase()} | **Target Duration:** ${duration} Minutes\n`;
    md += `> **Generated on:** ${new Date().toLocaleDateString()} via ShikshakAI Adaptive Educator\n\n`;
    md += `---\n\n`;

    md += `## 1. Executive Summary\n\n`;
    md += `This study guide covers the fundamental principles, mechanisms, and real-world applications of **${topic}**.\n\n`;

    md += `## 2. Structured Lesson Breakdown\n\n`;
    steps.forEach((s, idx) => {
      md += `### Step ${idx + 1}: ${s.step_type.toUpperCase()} — ${s.visual?.title || "Key Concept"}\n\n`;
      md += `**Teacher Explanation:**\n> "${s.teacher_script}"\n\n`;

      if (s.visual) {
        if (s.visual.type === "code") {
          md += `**Code Demonstration:**\n\`\`\`python\n${s.visual.content}\n\`\`\`\n\n`;
        } else if (s.visual.type === "katex") {
          md += `**Mathematical Formula:**\n$$\n${s.visual.content}\n$$\n\n`;
        } else if (s.visual.type === "bullet_points") {
          md += `**Key Points:**\n${s.visual.content}\n\n`;
        } else if (s.visual.type === "mermaid") {
          md += `**Conceptual Architecture / Diagram:**\n\`\`\`mermaid\n${s.visual.content}\n\`\`\`\n\n`;
        }
      }

      if (s.question) {
        md += `**Checkpoint Question:**\n*${s.question}*\n\n`;
        if (s.options) {
          s.options.forEach((opt, optIdx) => {
            const letter = String.fromCharCode(65 + optIdx);
            md += `- **(${letter})** ${opt}\n`;
          });
          md += `\n`;
        }
        if (s.correct_answer) {
          md += `**Correct Answer:** \`${s.correct_answer}\`\n\n`;
        }
        if (s.misconception_guide) {
          md += `**Intuition Guide & Misconceptions:**\n*${s.misconception_guide}*\n\n`;
        }
      }
      md += `---\n\n`;
    });

    md += `## 3. High-Yield Revision Checklist\n\n`;
    md += `- [ ] Master core definition and working drivers of ${topic}.\n`;
    md += `- [ ] Practice explaining ${topic} without looking at reference notes.\n`;
    md += `- [ ] Solve 3 applied checkpoint questions.\n\n`;
    md += `---\n*Generated by ShikshakAI — Adaptive AI Video & Concept Educator*`;

    return md;
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownNotes();
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${topic.replace(/[^a-zA-Z0-9_-]/g, "_")}_Study_Notes.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    const md = generateMarkdownNotes();
    const plainText = md.replace(/[#*`_>]/g, "");
    const blob = new Blob([plainText], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${topic.replace(/[^a-zA-Z0-9_-]/g, "_")}_Notes.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    const md = generateMarkdownNotes();
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="study-notes-modal-overlay" onClick={onClose}>
      <div className="study-notes-modal-card" onClick={(e) => e.stopPropagation()}>
        {/* Modal Header */}
        <div className="notes-modal-header">
          <div className="notes-header-meta">
            <div className="notes-icon-badge">
              <FileText size={20} className="text-indigo-400" />
            </div>
            <div>
              <h3 className="notes-modal-title">{topic} — Complete Study Notes</h3>
              <p className="notes-modal-subtitle">
                Instructor: {teacherName} • {level.toUpperCase()} • {steps.length} Core Modules
              </p>
            </div>
          </div>

          <div className="notes-header-actions">
            <button
              type="button"
              className="notes-action-btn copy-btn"
              onClick={handleCopy}
              title="Copy markdown to clipboard"
            >
              {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
              <span>{copied ? "Copied!" : "Copy Notes"}</span>
            </button>

            <button
              type="button"
              className="notes-action-btn download-btn"
              onClick={handleDownloadMarkdown}
              title="Download as Markdown file (.md)"
            >
              <Download size={14} />
              <span>Download (.md)</span>
            </button>

            <button
              type="button"
              className="notes-action-btn print-btn"
              onClick={handlePrint}
              title="Print or Save as PDF"
            >
              <Printer size={14} />
              <span>Print / PDF</span>
            </button>

            <button
              type="button"
              className="notes-close-btn"
              onClick={onClose}
              aria-label="Close notes modal"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Modal Body: Rendered Study Guide Document */}
        <div className="notes-modal-body">
          {/* Executive Overview Banner */}
          <div className="notes-summary-box">
            <div className="summary-badge">
              <Lightbulb size={16} />
              <span>EXECUTIVE OVERVIEW</span>
            </div>
            <p className="summary-text">
              Comprehensive reference notes for <strong>{topic}</strong>. Includes intuitive teacher explanations, mathematical derivations, worked code snippets, and conceptual checkpoint assessments.
            </p>
          </div>

          {/* Step-by-Step Lecture Notes */}
          <div className="notes-sections-list">
            {steps.map((step, idx) => (
              <div key={idx} className="note-step-card">
                <div className="note-step-header">
                  <span className="note-step-num">Step {idx + 1}</span>
                  <h4 className="note-step-title">{step.visual?.title || `Module ${idx + 1}: ${step.step_type}`}</h4>
                  <span className="note-step-type">{step.step_type}</span>
                </div>

                {/* Teacher Script Transcript */}
                <div className="note-script-block">
                  <span className="script-label">Teacher Explanation:</span>
                  <p className="script-quote">"{step.teacher_script}"</p>
                </div>

                {/* Visual Artifact Demonstration */}
                {step.visual && (
                  <div className="note-visual-block">
                    <span className="visual-block-title">Key Visual / Demonstration:</span>
                    {step.visual.type === "code" && (
                      <pre className="note-code-snippet">
                        <code>{step.visual.content}</code>
                      </pre>
                    )}
                    {step.visual.type === "bullet_points" && (
                      <div className="note-bullet-points">
                        {step.visual.content.split("\n").map((pt, pIdx) => (
                          <div key={pIdx} className="note-bullet-line">
                            <CheckCircle2 size={14} className="text-indigo-400" />
                            <span>{pt.replace(/^[0-9]+\.\s*|\•\s*/, "")}</span>
                          </div>
                        ))}
                      </div>
                    )}
                    {step.visual.type === "katex" && (
                      <div className="note-formula-box">
                        <code>{step.visual.content}</code>
                      </div>
                    )}
                    {step.visual.type === "mermaid" && (
                      <div className="note-mermaid-desc">
                        <p className="diagram-caption">Diagram Structure: {step.visual.title}</p>
                        <pre className="diagram-pre"><code>{step.visual.content}</code></pre>
                      </div>
                    )}
                  </div>
                )}

                {/* Checkpoint Question & Pedagogical Guide */}
                {step.question && (
                  <div className="note-checkpoint-block">
                    <div className="checkpoint-q-head">
                      <HelpCircle size={16} className="text-amber-400" />
                      <h5>Assessment Checkpoint</h5>
                    </div>
                    <p className="note-q-text">{step.question}</p>
                    {step.options && (
                      <div className="note-options-grid">
                        {step.options.map((opt, optIdx) => (
                          <div
                            key={optIdx}
                            className={`note-option-pill ${
                              opt === step.correct_answer ? "is-correct" : ""
                            }`}
                          >
                            <span className="opt-letter">{String.fromCharCode(65 + optIdx)}</span>
                            <span>{opt}</span>
                            {opt === step.correct_answer && <span className="correct-tag">✓ Correct</span>}
                          </div>
                        ))}
                      </div>
                    )}
                    {step.misconception_guide && (
                      <p className="note-misc-guide">
                        <strong>Intuition Guide:</strong> {step.misconception_guide}
                      </p>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Modal Footer with quick export options */}
        <div className="notes-modal-footer">
          <span className="notes-footer-info">
            Downloaded notes are 100% formatted for Notion, Obsidian, and Markdown editors.
          </span>
          <div className="notes-footer-buttons">
            <button type="button" className="footer-btn text-btn" onClick={handleDownloadText}>
              Download (.txt)
            </button>
            <button type="button" className="footer-btn md-btn" onClick={handleDownloadMarkdown}>
              <Download size={14} />
              <span>Download Markdown (.md)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
